### ISSUE TITLE
Messages in HTML

### ISSUE THREAD

**Issue by robmachado** [yoeunes/notify#15]
I'm looking for a way to put the message in html to SweetAlert2.
Is this something I can determine in config / notify.php ??
Or is there currently no way to do this?

**Comment by ldelcasti** [comment]
Hi @robmachado , you need to modify the sweetalert2.php file.

notify/src/Notifiers/SweetAlert2.php

` if (empty($options)) {
            return "toast({title:'$title', html:'$message', type:'$type'});";
        }

        return "toast({title:'$title', html:'$message', type:'$type', $options});";`

**Comment by robmachado** [comment]
Tks ! 
Seizing the opportunity I wish you a great 2021
