### ISSUE TITLE
Question: Dynamically change driver at runtime 

### ISSUE THREAD

**Issue by eddielee394** [yoeunes/notify#4]
Is there currently any method that allows you to swap the alert drivers without changing the `config.notify.default` setting ?  For example, if we wanted to display a sweetalert instead of a toastr?

**Comment by yoeunes** [comment]
hello @eddielee394 sorry for the late response, for the time being their is no option to swap the default driver, i will implement it later, thank you for the great idea, did you try to change it dynamicaly in the configuration at anytime in your code :


```php
config(['notify.default' => 'toastr']);
```
