### ISSUE TITLE
Documentation syntax error: timeOut

### ISSUE THREAD

**Issue by lhilton** [yoeunes/notify#8]
# Description
The README.md shows incorrect syntax for setting the notification timeout.

## Steps To Reproduce
Add this code to a controller action:
```
notify()->success('We do have the Kapua suite available.', 'Turtle Bay Resort', ['timeOut': 5000])
```
You will recieve this error on the route for that controller action:
```
syntax error, unexpected ':', expecting ']'
```

## Expected behavior
Awesome notification with overridden property

**Comment by yoeunes** [comment]
thank u again Mr @lhilton

**Comment by lhilton** [comment]
No problem. Fantastic module, I love the design and how you structured it. Just flexible enough to fit a lot of solutions without being uselessly generic. Right in the sweet spot.
